config/routes.rb
Rails.application.routes.draw do
  
  resources :awesomes
  root "awesomes#index"

end

app/models/awesome.rb
class Awesome < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/awesomes_controller.rb
class AwesomesController < ApplicationController
  before_action :set_awesome, only: [:show, :edit, :update, :destroy]

  # GET /awesomes
  # GET /awesomes.json
  def index
    @awesomes = Awesome.all
  end

  # GET /awesomes/1
  # GET /awesomes/1.json
  def show
  end

  # GET /awesomes/new
  def new
    @awesome = Awesome.new
  end

  # GET /awesomes/1/edit
  def edit
  end

  # POST /awesomes
  # POST /awesomes.json
  def create
    @awesome = Awesome.new(awesome_params)

    respond_to do |format|
      if @awesome.save
        format.html { redirect_to @awesome, notice: 'Awesome was successfully created.' }
        format.json { render :show, status: :created, location: @awesome }
      else
        format.html { render :new }
        format.json { render json: @awesome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awesomes/1
  # PATCH/PUT /awesomes/1.json
  def update
    respond_to do |format|
      if @awesome.update(awesome_params)
        format.html { redirect_to @awesome, notice: 'Awesome was successfully updated.' }
        format.json { render :show, status: :ok, location: @awesome }
      else
        format.html { render :edit }
        format.json { render json: @awesome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awesomes/1
  # DELETE /awesomes/1.json
  def destroy
    @awesome.destroy
    respond_to do |format|
      format.html { redirect_to awesomes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_awesome
      @awesome = Awesome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def awesome_params
      params.require(:awesome).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awesomes_helper.rb
module AwesomesHelper
end

app/views/awesomes/_form.html.erb
<%= form_for(@awesome) do |f| %>
  <% if @awesome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@awesome.errors.count, "error") %> prohibited this awesome from being saved:</h2>

      <ul>
      <% @awesome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/awesomes/edit.html.erb
<h1>Editing awesome</h1>

<%= render 'form' %>

<%= link_to 'Show', @awesome %> |
<%= link_to 'Back', awesomes_path %>

app/views/awesomes/index.html.erb
<h1>Listing awesomes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @awesomes.each do |awesome| %>
      <tr>
        <td><%= awesome.name %></td>
        <td><%= link_to 'Show', awesome %></td>
        <td><%= link_to 'Edit', edit_awesome_path(awesome) %></td>
        <td><%= link_to 'Destroy', awesome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Awesome', new_awesome_path %>

app/views/awesomes/new.html.erb
<h1>New awesome</h1>

<%= render 'form' %>

<%= link_to 'Back', awesomes_path %>

app/views/awesomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @awesome.name %>
</p>

<%= link_to 'Edit', edit_awesome_path(@awesome) %> |
<%= link_to 'Back', awesomes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleSidekiq</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>